"""Table of the networks on the published libRadtran benchmark (paper, Section 6.2) from the records in results/pkan.

Reads results/pkan/p3pk_s*.json (one record per seed, written by p3_pkan.py) and writes paper/table_pkan.tex: the
forward scores in the release's metric formulas and the retrieval scores of Section 5, mean and standard deviation over
the seeds, with the published values of the release's two best models and 6S used as the emulator. Prints the paired
counts quoted in the text.

usage: python code/make_pkan_table.py [--records results/pkan] [--out paper/table_pkan.tex]
"""
import argparse
import glob
import json
import os

import numpy as np

ap = argparse.ArgumentParser()
ap.add_argument("--records", default="results/pkan")
ap.add_argument("--out", default="paper/table_pkan.tex")
args = ap.parse_args()

recs = [json.load(open(p)) for p in sorted(glob.glob(os.path.join(args.records, "p3pk_s*.json")))]
assert recs, "no records"
assert len({r["data_sha256"] for r in recs}) == 1 and len({r["driver_sha256"] for r in recs}) == 1
print(f"{len(recs)} seeds {[r['seed'] for r in recs]}, epochs {recs[0]['epochs']}, width {recs[0]['width']}, depth "
      f"{recs[0]['depth']}, rows {recs[0]['rows']}, states {recs[0]['states']}")

ARMS = [("plain", "network, plain"), ("floored@0.1", "network, floored, $u=10^{-1}$"),
        ("flat0.5@0.01", "network, flattened, $\\kappa=1/2$, $u=10^{-2}$")]
FWD = [("rmse", 5), ("mae", 5), ("r2", 4), ("smape", 2)]
COMP = ["rho_path", "T_total", "spher_alb"]
RET = [("radiance", 3), ("allband_p95", 2), ("p95@1e-12", 2), ("p95@0.001", 2), ("p95@0.01", 2), ("failed_pct@0.001", 3)]


def arm_vals(r, arm):
    return r["six_s_baseline"] if arm == "6S" else r["arms"][arm]


def stat(arm, get):
    v = np.array([get(arm_vals(r, arm)) for r in recs], float)
    return v.mean(), (v.std(ddof=1) if len(v) > 1 else 0.0), v


def cell(m, s, nd, sd=True):
    return f"${m:.{nd}f}$" if not sd else f"${m:.{nd}f}\\pm{s:.{nd}f}$"


lines = ["% generated by code/make_pkan_table.py from results/pkan; do not edit by hand",
         "\\begin{tabular}{@{}lcccccccc@{}}", "\\toprule",
         " & RMSE & MAE & $R^2$ & SMAPE [\\%] & \\multicolumn{3}{c}{RMSE by coefficient} & \\\\",
         "\\cmidrule(lr){6-8}",
         "emulator & & & & & $\\rho_{\\rm path}$ & $T$ & $S$ & \\\\", "\\midrule"]
pub = recs[0]["published"]
table3 = json.load(open(os.path.join(args.records, "published_table3.json")))
for p in table3["models"]:
    # the release's values for its two best models must equal those the driver recorded at run time
    if p["model"] == "pKANrtm":
        assert abs(p["rmse"] - pub["pKANrtm_standard_split"]["rmse"]) < 1e-9
    if p["model"] == "sRTMNet":
        assert abs(p["rmse"] - pub["sRTMNet_style_standard_split"]["rmse"]) < 1e-9
    name = {"pKANrtm": "pKANrtm \\cite{pkan}",
            "sRTMNet": "sRTMnet \\cite{brodrick}, trained in \\cite{pkan}"}.get(p["model"], p["model"] + " \\cite{pkan}")
    lines.append(f"{name} & ${p['rmse']:.5f}$ & ${p['mae']:.5f}$ & ${p['r2']:.4f}$ & ${p['smape']:.2f}$ & & & & \\\\")
lines.append("\\midrule")
for arm, name in [("6S", "6S as the emulator")] + ARMS:
    row = [name]
    for k, nd in FWD:
        m, s, _ = stat(arm, lambda a, k=k: a["pkan_metrics"]["overall"][k])
        row.append(cell(m, s, nd, sd=arm != "6S"))
    for c in COMP:
        m, s, _ = stat(arm, lambda a, c=c: a["pkan_metrics"][c]["rmse"])
        row.append(cell(m, s, 5, sd=arm != "6S"))
    lines.append(" & ".join(row) + " & \\\\")
lines += ["\\midrule",
          " & radiance [\\%] & all bands & phys.\\ $10^{-12}$ & phys.\\ $10^{-3}$ & phys.\\ $10^{-2}$ & failed [\\%] & & \\\\",
          "\\midrule"]
for arm, name in [("6S", "6S as the emulator")] + ARMS:
    row = [name]
    for k, nd in RET:
        m, s, _ = stat(arm, lambda a, k=k: a["retrieval"][k])
        row.append(cell(m, s, nd, sd=arm != "6S"))
    lines.append(" & ".join(row) + " & & \\\\")
lines += ["\\bottomrule", "\\end{tabular}"]
os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
open(args.out, "w", encoding="utf-8").write("\n".join(lines) + "\n")
print("wrote", args.out)

# paired counts against the plain network, quoted in the text
lower = {"rmse": True, "mae": True, "r2": False, "smape": True}
for arm, _ in ARMS[1:]:
    out = []
    for k in lower:
        _, _, a = stat(arm, lambda x, k=k: x["pkan_metrics"]["overall"][k])
        _, _, p = stat("plain", lambda x, k=k: x["pkan_metrics"]["overall"][k])
        out.append(f"{k} {int(((a < p) if lower[k] else (a > p)).sum())}")
    for c in COMP:
        _, _, a = stat(arm, lambda x, c=c: x["pkan_metrics"][c]["rmse"])
        _, _, p = stat("plain", lambda x, c=c: x["pkan_metrics"][c]["rmse"])
        out.append(f"{c} {int((a < p).sum())}")
    for k, _ in RET:
        _, _, a = stat(arm, lambda x, k=k: x["retrieval"][k])
        _, _, p = stat("plain", lambda x, k=k: x["retrieval"][k])
        out.append(f"{k} {int((a < p).sum())}")
    print(f"{arm}: seeds better than plain of {len(recs)}: " + ", ".join(out))
for arm, _ in ARMS:
    print(arm, "best epochs", [r["arms"][arm]["best_epoch"] for r in recs])
m_p, _, _ = stat("plain", lambda a: a["retrieval"]["radiance"])
for arm, _ in ARMS[1:]:
    m, _, _ = stat(arm, lambda a: a["retrieval"]["radiance"])
    mae, _, _ = stat(arm, lambda a: a["pkan_metrics"]["overall"]["mae"])
    rm, _, _ = stat(arm, lambda a: a["pkan_metrics"]["overall"]["rmse"])
    print(f"{arm}: radiance {m_p:.3f} -> {m:.3f} ({m / m_p:.2f}x); MAE / pKANrtm {mae / pub['pKANrtm_standard_split']['mae']:.2f}; "
          f"RMSE / pKANrtm {rm / pub['pKANrtm_standard_split']['rmse']:.2f}")
