"""Tables of the principal networks across surface reflectances, with failed inversions counted as infinite errors.

  paper/table_rho_pkan.tex   the libRadtran benchmark, from results/pkan2_rescore (p3_rescore_pkan.py): the release's
                             split (ten seeds) and the out-of-distribution split (five seeds)
  paper/table_rho_emit.tex   the EMIT table without its two failed evaluations: the paper's networks from
                             results/dgx/p3pr_rescore (p3_rescore_emit.py on the p3pr runs) and the emulators of the
                             second paper from results/dgx/members_rescore (p3_rescore_members.py), ten splits each

Each cell is the mean over seeds or splits; the script also prints, for every network, reflectance and score, on how many
seeds or splits it is below the plain network.

usage: python code/make_rho_tables.py
"""
import glob
import json
import math
import os
import statistics as st

RHOS = ["0.1", "0.4", "0.7", "0.9"]
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def load(pattern):
    return [json.load(open(f, encoding="utf-8")) for f in sorted(glob.glob(os.path.join(ROOT, pattern)))]


def mean(xs):
    return float("inf") if any(math.isinf(x) for x in xs) else st.mean(xs)


def fmt(x, d):
    return r"$\infty$" if math.isinf(x) else f"${x:.{d}f}$"


def wins(recs, arm, rho, key):
    return sum(1 for r in recs if r["arms"][arm][rho][key] < r["arms"]["plain"][rho][key])


def report(name, recs, arms, keys):
    print(f"== {name}: {len(recs)} runs")
    for rho in RHOS:
        for arm, _ in arms[1:]:
            print(f"  rho {rho} {arm:22s} " + "  ".join(f"{k} {mean([r['arms'][arm][rho][k] for r in recs]):.4g} "
                                                          f"(lower {wins(recs, arm, rho, k)}/{len(recs)})" for k in keys))


PK_ARMS = [("plain", "plain"), ("floored@0.1", r"floored, $u=10^{-1}$"),
           ("flat0.5@0.01", r"flattened, $\kappa=1/2$, $u=10^{-2}$"), ("mix0.3:flat0.5@0.01", r"$0.3$ plain $+\,0.7$ flattened")]
off, ood = load("results/pkan2_rescore/p3pk2_off_s*.json"), load("results/pkan2_rescore/p3pk2_ood_s*.json")
assert len(off) == 10 and len(ood) == 5, (len(off), len(ood))
K = ["radiance", "p95@1e-12", "p95@0.001", "failed_pct@1e-12", "failed_pct@0.001"]
rows = []
for rho in RHOS:
    for i, (arm, label) in enumerate(PK_ARMS):
        cells = []
        for recs in (off, ood):
            v = [mean([r["arms"][arm][rho][k] for r in recs]) for k in K]
            cells += [fmt(v[0], 3), fmt(v[1], 2), fmt(v[2], 2), fmt(v[3], 2), fmt(v[4], 3)]
        rows.append((f"${rho}$" if i == 0 else "") + " & " + label + " & " + " & ".join(cells) + r" \\")
    rows.append(r"\addlinespace")
rows.pop()
tex = [r"% generated by code/make_rho_tables.py from results/pkan2_rescore; do not edit by hand",
       r"\begin{tabular}{@{}llcccccccccc@{}}", r"\toprule",
       r" & & \multicolumn{5}{c}{the release's split} & \multicolumn{5}{c}{out-of-distribution split} \\",
       r"\cmidrule(lr){3-7}\cmidrule(l){8-12}",
       r" & & & \multicolumn{2}{c}{tail, phys.} & \multicolumn{2}{c}{failed [\%], phys.} & "
       r" & \multicolumn{2}{c}{tail, phys.} & \multicolumn{2}{c}{failed [\%], phys.} \\",
       r"\cmidrule(lr){4-5}\cmidrule(lr){6-7}\cmidrule(lr){9-10}\cmidrule(l){11-12}",
       r"$\rho$ & network & radiance [\%] & $10^{-12}$ & $10^{-3}$ & $10^{-12}$ & $10^{-3}$ & radiance [\%] & "
       r"$10^{-12}$ & $10^{-3}$ & $10^{-12}$ & $10^{-3}$ \\", r"\midrule"] + rows + [r"\bottomrule", r"\end{tabular}"]
open(os.path.join(ROOT, "paper", "table_rho_pkan.tex"), "w", encoding="utf-8", newline="\n").write("\n".join(tex) + "\n")
report("benchmark, release split", off, PK_ARMS, K)
report("benchmark, out-of-distribution split", ood, PK_ARMS, K)
# the failure-inclusive tails against the failure-excluding ones of the first version, at rho = 0.7
for name, recs in (("release split", off), ("ood split", ood)):
    d = max(abs(r["arms"][a]["0.7"][f"p95@{f}"] - r["arms"][a]["0.7"][f"p95x@{f}"]) for r in recs for a, _ in PK_ARMS
            for f in ("1e-12", "0.001", "0.01"))
    print(f"  {name}: largest gap between failure-including and failure-excluding tails at rho 0.7: {d:.3f} points")

EM_ARMS = [("plain", "plain"), ("w1_u0.1", r"floored, $u=10^{-1}$"), ("flat0.5_u0.01", r"flattened, $\kappa=1/2$, $u=10^{-2}$")]
# the emulators of the second paper, from their saved predictions (p3_rescore_members.py): (family, width, label)
MEMBERS = [("krr", 512, r"Mat\'ern kernel, isotropic"), ("ard", 512, r"Mat\'ern kernel, input-scaled"),
           ("dnn_corr", 512, r"network with kernel correction"), ("dkr", 512, r"kernel on features, width $512$"),
           ("dkr", 2000, r"kernel on features, width $2000$"), ("stack", 512, r"convex stack, width $512$"),
           ("stack", 2000, r"convex stack, width $2000$")]
emit = load("results/dgx/p3pr_rescore/p3pr_s*.json")
mem = {w: load(f"results/dgx/members_rescore/members_s*_w{w}.json") for w in (512, 2000)}
if emit:
    assert len(emit) == 10 and all(len(v) == 10 for v in mem.values()), (len(emit), {w: len(v) for w, v in mem.items()})

    def cells(get):
        v07 = [get("0.7", k) for k in ("radiance", "allband_p95", "p95@1e-12")]
        tails = [get(r, "p95@0.001") for r in RHOS]
        return ([fmt(v07[0], 3), fmt(v07[1], 1), fmt(v07[2], 2)] + [fmt(x, 2) for x in tails]
                + [fmt(get("0.7", "failed_pct@1e-12"), 2), fmt(get("0.7", "failed_pct@0.001"), 3)])
    rows = [r"\multicolumn{10}{@{}l}{\emph{networks of this paper}}\\"]
    for arm, label in EM_ARMS:
        rows.append(label + " & " + " & ".join(cells(lambda r, k: mean([x["arms"][arm][r][k] for x in emit]))) + r" \\")
    rows += [r"\addlinespace", r"\multicolumn{10}{@{}l}{\emph{emulators of \cite{shmalo2}}}\\"]
    for fam, w, label in MEMBERS:
        rows.append(label + " & " + " & ".join(cells(lambda r, k: mean([x["families"][fam][r][k] for x in mem[w]]))) + r" \\")
    tex = [r"% generated by code/make_rho_tables.py from results/dgx/p3pr_rescore and results/dgx/members_rescore; do not edit by hand",
           r"\begin{tabular}{@{}lccccccccc@{}}", r"\toprule",
           r" & \multicolumn{3}{c}{$\rho=0.7$} & \multicolumn{4}{c}{tail, phys.\ $10^{-3}$} & \multicolumn{2}{c}{failed [\%], $\rho=0.7$} \\",
           r"\cmidrule(lr){2-4}\cmidrule(lr){5-8}\cmidrule(l){9-10}",
           r"emulator & radiance [\%] & all bands & phys.\ $10^{-12}$ & $\rho=0.1$ & $0.4$ & $0.7$ & $0.9$ & "
           r"phys.\ $10^{-12}$ & phys.\ $10^{-3}$ \\",
           r"\midrule"] + rows + [r"\bottomrule", r"\end{tabular}"]
    open(os.path.join(ROOT, "paper", "table_rho_emit.tex"), "w", encoding="utf-8", newline="\n").write("\n".join(tex) + "\n")
    KE = ["radiance", "allband_p95", "p95@1e-12", "p95@0.001", "p95@0.01", "failed_pct@1e-12", "failed_pct@0.001"]
    report("EMIT, ten splits", emit, EM_ARMS, KE)
    for fam, w, label in MEMBERS:
        print(f"  {fam} w{w}: " + "  ".join(f"rho {r} " + " ".join(f"{k} {mean([x['families'][fam][r][k] for x in mem[w]]):.4g}"
                                                                     for k in ("radiance", "p95@1e-12", "p95@0.001", "failed_pct@0.001"))
                                            for r in RHOS))
else:
    print("no EMIT rescoring records yet (results/dgx/p3pr_rescore)")
